import { EventEmitter } from './event-emitter.js'

const DEFAULT_RTC_CONFIG = {
  iceServers: [
    { urls: ['stun:stun.l.google.com:19302', 'stun:stun1.l.google.com:19302'] },
  ],
}

// For local P2P (same WiFi / same machine), we include a STUN server to ensure
// Firefox starts ICE gathering properly. Host candidates (local IP / mDNS) are
// what actually get used for same-machine connections; srflx candidates are
// ignored but harmless.
const LOCAL_RTC_CONFIG = {
  iceServers: [
    { urls: ['stun:stun.l.google.com:19302'] },
  ],
}

function waitForIceComplete(pc) {
  return new Promise(resolve => {
    if (pc.iceGatheringState === 'complete') {
      resolve()
      return
    }
    const onStateChange = () => {
      if (pc.iceGatheringState === 'complete') {
        pc.removeEventListener('icegatheringstatechange', onStateChange)
        resolve()
      }
    }
    pc.addEventListener('icegatheringstatechange', onStateChange)
  })
}

function createPeerConnection(config = DEFAULT_RTC_CONFIG) {
  return new RTCPeerConnection(config)
}

// Local peer-to-peer adapter using native WebRTC data channels.
// Signaling (offer/answer exchange) is intentionally out-of-band so that
// two devices in the same WiFi can connect without a dedicated game server.
// The UI wraps the offer/answer strings in QR codes or lets the user copy them.
export class WebRTCAdapter extends EventEmitter {
  constructor() {
    super()
    this.pc = null
    this.channel = null
    this.role = null
    this.pendingCandidates = []
  }

  // Host side: create an offer and return the full SDP string.
  async createHostOffer(rtcConfig = LOCAL_RTC_CONFIG) {
    this.role = 'host'
    this.pc = createPeerConnection(rtcConfig)
    this._bindConnection()

    this.channel = this.pc.createDataChannel('cave-channel', {
      ordered: false,
      maxRetransmits: 0,
    })
    this._bindDataChannel(this.channel)

    const offer = await this.pc.createOffer()
    await this.pc.setLocalDescription(offer)
    await waitForIceComplete(this.pc)
    this._logIceCandidates('host/offer')
    return this.pc.localDescription.sdp
  }

  // Host side: accept the answer SDP generated by the client.
  async acceptClientAnswer(answerSdp) {
    if (!this.pc || this.role !== 'host') {
      throw new Error('Not in host mode')
    }
    console.log(`[WEBRTC_host] Setting remote description (answer), SDP length:`, answerSdp.length)
    const remoteCandidates = [...answerSdp.matchAll(/a=candidate:(.*)/g)].map(m => m[1])
    console.log(`[WEBRTC_host] Remote answer contains ${remoteCandidates.length} ICE candidates:`)
    for (const c of remoteCandidates) {
      console.log(`[WEBRTC_host]   remote: ${c}`)
    }
    await this.pc.setRemoteDescription({ type: 'answer', sdp: answerSdp })
    console.log(`[WEBRTC_host] Remote description set successfully`)
  }

  // Client side: connect to a host using its offer SDP and return an answer.
  async connectToHost(offerSdp, rtcConfig = LOCAL_RTC_CONFIG) {
    this.role = 'client'
    this.pc = createPeerConnection(rtcConfig)
    this._bindConnection()

    this.pc.ondatachannel = (event) => {
      this.channel = event.channel
      this._bindDataChannel(this.channel)
    }

    await this.pc.setRemoteDescription({ type: 'offer', sdp: offerSdp })
    const answer = await this.pc.createAnswer()
    await this.pc.setLocalDescription(answer)
    await waitForIceComplete(this.pc)
    this._logIceCandidates('client/answer')
    return this.pc.localDescription.sdp
  }

  _bindConnection() {
    const pc = this.pc
    pc.addEventListener('connectionstatechange', () => {
      console.log(`[WEBRTC_${this.role}] connectionState:`, pc.connectionState)
      if (pc.connectionState === 'connected') {
        this.emit('connected')
      } else if (['disconnected', 'failed', 'closed'].includes(pc.connectionState)) {
        this.emit('disconnected')
      }
    })
    pc.addEventListener('iceconnectionstatechange', () => {
      console.log(`[WEBRTC_${this.role}] iceConnectionState:`, pc.iceConnectionState)
      if (pc.iceConnectionState === 'failed') {
        const stats = pc.getStats ? pc.getStats() : null
        if (stats) {
          stats.then(report => {
            report.forEach((item, key) => {
              if (item.type === 'candidate-pair' && item.state === 'failed') {
                console.error(`[WEBRTC_${this.role}] Failed candidate pair:`, {
                  local: item.localCandidateId,
                  remote: item.remoteCandidateId,
                  nominated: item.nominated,
                })
              }
              if (item.type === 'local-candidate' || item.type === 'remote-candidate') {
                console.log(`[WEBRTC_${this.role}] ${item.type}:`, item.candidateType, item.address, item.port, item.protocol)
              }
            })
          })
        }
      }
    })
    pc.addEventListener('icegatheringstatechange', () => {
      console.log(`[WEBRTC_${this.role}] iceGatheringState:`, pc.iceGatheringState)
    })
    pc.addEventListener('icecandidate', (e) => {
      if (e.candidate) {
        console.log(`[WEBRTC_${this.role}] ICE candidate found:`, e.candidate.candidate)
      } else {
        console.log(`[WEBRTC_${this.role}] ICE candidate gathering complete (null candidate)`)
      }
    })
    pc.addEventListener('icecandidateerror', (e) => {
      console.error(`[WEBRTC_${this.role}] ICE candidate error:`, e.errorText, 'code:', e.errorCode, 'url:', e.url)
      this.emit('error', { message: `ICE candidate error: ${e.errorText}` })
    })
  }

  _logIceCandidates(label) {
    const sdp = this.pc.localDescription?.sdp || ''
    const candidates = [...sdp.matchAll(/a=candidate:(.*)/g)].map(m => m[1])
    console.log(`[WEBRTC_${this.role}] ICE candidates (${label}):`, candidates.length)
    for (const c of candidates) {
      console.log(`[WEBRTC_${this.role}]   ${c}`)
    }
    if (candidates.length === 0) {
      console.warn(`[WEBRTC_${this.role}] No ICE candidates gathered! SDP:`, sdp.substring(0, 200))
    }
  }

  _bindDataChannel(channel) {
    channel.addEventListener('open', () => {
      this.emit('data-channel-open')
    })
    channel.addEventListener('close', () => {
      this.emit('data-channel-close')
    })
    channel.addEventListener('message', (event) => {
      try {
        const { t, p } = JSON.parse(event.data)
        if (t === 'game:ping') {
          this.send('game:pong', p)
          return
        }
        this.emit(t, p)
      } catch {
        // Ignore malformed messages
      }
    })
  }

  send(type, payload) {
    if (this.channel && this.channel.readyState === 'open') {
      this.channel.send(JSON.stringify({ t: type, p: payload }))
    }
  }

  close() {
    if (this.channel) {
      this.channel.close()
      this.channel = null
    }
    if (this.pc) {
      this.pc.close()
      this.pc = null
    }
  }
}
